package Comphex;

public class Theme {

    public static final String[] THEMES = new String[]{
        "com.formdev.flatlaf.intellijthemes.FlatArcIJTheme", "com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme", "com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme", "com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme", "com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme", "com.formdev.flatlaf.intellijthemes.FlatCobalt2IJTheme", "com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme", "com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme", "com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme", "com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme",
        "com.formdev.flatlaf.intellijthemes.FlatGradiantoDarkFuchsiaIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGradiantoDeepOceanIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGradiantoMidnightBlueIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGrayIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkHardIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkMediumIJTheme", "com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkSoftIJTheme", "com.formdev.flatlaf.intellijthemes.FlatHiberbeeDarkIJTheme", "com.formdev.flatlaf.intellijthemes.FlatHighContrastIJTheme",
        "com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme", "com.formdev.flatlaf.intellijthemes.FlatMaterialDesignDarkIJTheme", "com.formdev.flatlaf.intellijthemes.FlatMonocaiIJTheme", "com.formdev.flatlaf.intellijthemes.FlatNordIJTheme", "com.formdev.flatlaf.intellijthemes.FlatOneDarkIJTheme", "com.formdev.flatlaf.intellijthemes.FlatSolarizedDarkIJTheme", "com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme", "com.formdev.flatlaf.intellijthemes.FlatSpacegrayIJTheme", "com.formdev.flatlaf.intellijthemes.FlatVuesionIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkIJTheme",
        "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneLightIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneLightContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatDraculaContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkIJTheme",
        "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialOceanicIJTheme",
        "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialOceanicContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialPalenightIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialPalenightContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMonokaiProIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMonokaiProContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMoonlightIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMoonlightContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatNightOwlContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatSolarizedDarkIJTheme",
        "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatSolarizedDarkContrastIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatSolarizedLightIJTheme", "com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatSolarizedLightContrastIJTheme"};

    public static final String[] NAMES = new String[]{
        "Arc", "Arc - Orange", "Arc Dark", "Arc Dark - Orange", "Carbon", "Cobalt 2", "Cyan light", "Dark Flat", "Dark purple", "Dracula",
        "Gradianto Dark Fuchsia", "Gradianto Deep Ocean", "Gradianto Midnight Blue", "Gradianto Nature Green", "Gray", "Gruvbox Dark Hard", "Gruvbox Dark Medium", "Gruvbox Dark Soft", "Hiberbee Dark", "High contrast",
        "Light Flat", "Material Design Dark", "Monocai", "Nord", "One Dark", "Solarized Dark", "Solarized Light", "Spacegray", "Vuesion", "Arc Dark (Material)",
        "Arc Dark Contrast (Material)", "Atom One Dark (Material)", "Atom One Dark Contrast (Material)", "Atom One Light (Material)", "Atom One Light Contrast (Material)", "Dracula (Material)", "Dracula Contrast (Material)", "GitHub (Material)", "GitHub Contrast (Material)", "GitHub Dark (Material)",
        "GitHub Dark Contrast (Material)", "Light Owl (Material)", "Light Owl Contrast (Material)", "Material Darker (Material)", "Material Darker Contrast (Material)", "Material Deep Ocean (Material)", "Material Deep Ocean Contrast (Material)", "Material Lighter (Material)", "Material Lighter Contrast (Material)", "Material Oceanic (Material)",
        "Material Oceanic Contrast (Material)", "Material Palenight (Material)", "Material Palenight Contrast (Material)", "Monokai Pro (Material)", "Monokai Pro Contrast (Material)", "Moonlight (Material)", "Moonlight Contrast (Material)", "Night Owl (Material)", "Night Owl Contrast (Material)", "Solarized Dark (Material)",
        "Solarized Dark Contrast (Material)", "Solarized Light (Material)", "Solarized Light Contrast (Material)"};
}
